# Generated by Django 5.1.6 on 2025-12-12 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuyWise_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('target_price', models.FloatField()),
                ('product_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuyWise_app.user')),
            ],
        ),
    ]
