# Generated by Django 5.1.6 on 2025-12-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuyWise_app', '0002_pricealert'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('old_price', models.FloatField()),
                ('new_price', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
