# Generated by Django 5.1.6 on 2025-12-31 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuyWise_app', '0004_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricealert',
            name='current_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
