# Generated by Django 5.2.5 on 2026-02-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuyWise_app', '0005_pricealert_current_price_pricealert_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
